export default {
  notes: [
    'Ab',
    'A',
    'A#',
    'Bb',
    'B',
    'C',
    'C#',
    'Db',
    'D',
    'D#',
    'Eb',
    'E',
    'F',
    'F#',
    'Gb',
    'G',
    'G#',
  ],

  octaves: [3, 4],

  chords: [
    { value: 'maj', level: 'easy' },
    { value: 'maj#4', level: 'medium' },
    { value: 'maj7', level: 'easy' },
    { value: 'maj7#5', level: 'hard' },
    { value: 'maj9', level: 'medium' },
    { value: '/3', level: 'medium' },
    { value: '/5', level: 'medium' },
    { value: '6', level: 'easy' },

    { value: 'min', level: 'easy' },
    { value: 'm6', level: 'medium' },
    { value: 'min7', level: 'easy' },
    { value: 'm7b5', level: 'medium' },
    { value: 'm9', level: 'medium' },
    { value: 'm69', level: 'hard' },

    { value: 'sus2', level: 'easy' },
    { value: 'sus4', level: 'easy' },
    { value: '7sus', level: 'medium' },
    { value: '9sus', level: 'medium' },

    { value: '7', level: 'easy' },
    { value: '7b9', level: 'hard' },
    { value: '7#9', level: 'hard' },
    { value: '7#11', level: 'hard' },
    { value: '7b13', level: 'hard' },
    { value: '9', level: 'medium' },
    { value: '9#11', level: 'hard' },
    { value: '9b13', level: 'hard' },

    { value: 'dim', level: 'easy' },
    { value: 'dim7', level: 'medium' },

    { value: 'aug', level: 'easy' },
    { value: 'aug7', level: 'medium' },
  ],

  intervals: [
    { value: '1P', level: 'easy' },
    { value: '2m', level: 'easy' },
    { value: '2M', level: 'easy' },
    { value: '3m', level: 'easy' },
    { value: '3M', level: 'easy' },
    { value: '4P', level: 'easy' },
    { value: '5d', level: 'medium' },
    { value: '5P', level: 'easy' },
    { value: '6m', level: 'medium' },
    { value: '6M', level: 'easy' },
    { value: '7m', level: 'medium' },
    { value: '7M', level: 'easy' },
    { value: '8P', level: 'easy' },
    { value: '9m', level: 'medium' },
    { value: '9M', level: 'medium' },
  ],

  progressions: [
    { value: 'I, IV, V', level: 'easy' },
    { value: 'I, bVI, V', level: 'easy' },
    { value: 'I7, IV7, V7', level: 'easy' },
    { value: 'IV, IVm, I', level: 'easy' },
    { value: 'IV, V, I', level: 'easy' },
    { value: 'V, IV, I', level: 'easy' },
    { value: 'V7, IV7, I7', level: 'easy' },
    { value: 'bVI, bVII, I', level: 'medium' },
    { value: 'Im, bVI, bVII', level: 'medium' },
    { value: 'Im, IVm, bVII', level: 'medium' },
    { value: 'Im, IVm, Vm', level: 'easy' },
    { value: 'Im, IVm, Im', level: 'easy' },
    { value: 'IIm, V, I', level: 'easy' },
    { value: 'IIm, bVII7, I', level: 'medium' },
    { value: 'IIm7, V7, IMaj7', level: 'easy' },
    { value: 'IIm7, bII7, IMaj7', level: 'medium' },
    { value: 'IIm7b5, Vm, Im', level: 'medium' },
    { value: 'bVII, V7, I', level: 'medium' },
    { value: 'IIm, bIIIA, I', level: 'medium' },

    { value: 'I, V, VIm, IV', level: 'medium' },
    { value: 'I, IV, VIm, V', level: 'medium' },
    { value: 'I, V, IV, V', level: 'medium' },
    { value: 'I, VIm, IV, V', level: 'medium' },
    { value: 'I, bVII, IV, I', level: 'medium' },
    { value: 'I, III, IV, IVm', level: 'medium' },
    { value: 'I, IV, bVII, IV', level: 'medium' },
    { value: 'I, V, bVII, IV', level: 'medium' },
    { value: 'I, bVII, bVI, bVII', level: 'medium' },
    { value: 'I, VIm, IIm, V', level: 'medium' },
    { value: 'I, IV, IIm, V', level: 'medium' },
    { value: 'III7, VI7, II7, V7', level: 'medium' },
    { value: 'bVI, bVII, Im, Im', level: 'medium' },
    { value: 'VIm, V, IV, V', level: 'medium' },
    { value: 'VIm, IV, I, V', level: 'medium' },
    { value: 'VIm, IIIm, V, IV', level: 'medium' },
    { value: 'VIm, III, bII, I', level: 'medium' },
    { value: 'VIm, IIm, V, I', level: 'medium' },
    { value: 'Im, bVI, bIII, bVII', level: 'medium' },
    { value: 'Im, IVm, Vm, Im', level: 'medium' },
    { value: 'Im, bVII, bVI, bVII', level: 'medium' },
    { value: 'Im, Vm, bVII, IVm', level: 'medium' },
    { value: 'IIm, V, I, VIm', level: 'medium' },
  ],

  scales: [
    { value: 'major', level: 'easy' },
    { value: 'dorian', level: 'easy' },
    { value: 'dorian b2', level: 'hard' },
    { value: 'dorian #4', level: 'hard' },
    { value: 'phrygian', level: 'easy' },
    { value: 'phrygian dominant', level: 'hard' },
    { value: 'lydian', level: 'easy' },
    { value: 'lydian augmented', level: 'hard' },
    { value: 'lydian diminished', level: 'hard' },
    { value: 'lydian dominant', level: 'hard' },
    { value: 'mixolydian', level: 'easy' },
    { value: 'mixolydian b6', level: 'hard' },
    { value: 'minor', level: 'easy' },
    { value: 'locrian', level: 'easy' },
    { value: 'locrian #2', level: 'hard' },

    { value: 'augmented', level: 'medium' },
    { value: 'bebop', level: 'medium' },
    { value: 'chromatic', level: 'easy' },
    { value: 'diminished', level: 'medium' },
    { value: 'enigmatic', level: 'hard' },
    { value: 'flamenco', level: 'hard' },
    { value: 'half-whole diminished', level: 'medium' },
    { value: 'pelog', level: 'hard' },
    { value: 'persian', level: 'hard' },
    { value: 'prometheus', level: 'hard' },
    { value: 'whole tone', level: 'easy' },

    { value: 'major pentatonic', level: 'easy' },
    { value: 'major blues', level: 'medium' },
    { value: 'major augmented', level: 'medium' },
    { value: 'harmonic major', level: 'medium' },
    { value: 'double harmonic major', level: 'hard' },
    { value: 'neopolitan major', level: 'hard' },
    { value: 'bebop major', level: 'medium' },
    { value: 'hungarian major', level: 'hard' },
    { value: 'locrian major', level: 'hard' },

    { value: 'minor pentatonic', level: 'easy' },
    { value: 'minor six pentatonic', level: 'medium' },
    { value: 'minor blues', level: 'easy' },
    { value: 'minor hexatonic', level: 'hard' },
    { value: 'harmonic minor', level: 'medium' },
    { value: 'melodic minor', level: 'medium' },
    { value: 'hungarian minor', level: 'hard' },
  ],
};
