export default {
  notes: [
    'Ab',
    'A',
    'A#',
    'Bb',
    'B',
    'C',
    'C#',
    'Db',
    'D',
    'D#',
    'Eb',
    'E',
    'F',
    'F#',
    'Gb',
    'G',
    'G#',
  ],

  octaves: [3, 4],

  chords: [
    { value: 'maj' },
    { value: 'maj#4' },
    { value: 'maj7' },
    { value: 'maj7#5' },
    { value: 'maj9' },
    { value: '/3' },
    { value: '/5' },
    { value: '6' },

    { value: 'min' },
    { value: 'm6' },
    { value: 'min7' },
    { value: 'm7b5' },
    { value: 'm9' },
    { value: 'm69' },

    { value: 'sus2' },
    { value: 'sus4' },
    { value: '7sus' },
    { value: '9sus' },

    { value: '7' },
    { value: '7b9' },
    { value: '7#9' },
    { value: '7#11' },
    { value: '7b13' },
    { value: '9' },
    { value: '9#11' },
    { value: '9b13' },

    { value: 'dim' },
    { value: 'dim7' },

    { value: 'aug' },
    { value: 'aug7' },
  ],

  intervals: [
    { value: '1P' },
    { value: '2m' },
    { value: '2M' },
    { value: '3m' },
    { value: '3M' },
    { value: '4P' },
    { value: '5d' },
    { value: '5P' },
    { value: '6m' },
    { value: '6M' },
    { value: '7m' },
    { value: '7M' },
    { value: '8P' },
    { value: '9m' },
    { value: '9M' },
  ],

  progressions: [
    { value: 'I, IV, V' },
    { value: 'I, bVI, V' },
    { value: 'I7, IV7, V7' },
    { value: 'IV, IVm, I' },
    { value: 'IV, V, I' },
    { value: 'V, IV, I' },
    { value: 'V7, IV7, I7' },
    { value: 'bVI, bVII, I' },
    { value: 'Im, bVI, bVII' },
    { value: 'Im, IVm, bVII' },
    { value: 'Im, IVm, Vm' },
    { value: 'Im, IVm, Im' },
    { value: 'IIm, V, I' },
    { value: 'IIm, bVII7, I' },
    { value: 'IIm7, V7, IMaj7' },
    { value: 'IIm7, bII7, IMaj7' },
    { value: 'IIm7b5, Vm, Im' },
    { value: 'bVII, V7, I' },

    { value: 'I, V, VIm, IV' },
    { value: 'I, IV, VIm, V' },
    { value: 'I, V, IV, V' },
    { value: 'I, VIm, IV, V' },
    { value: 'I, bVII, IV, I' },
    { value: 'I, III, IV, IVm' },
    { value: 'I, IV, bVII, IV' },
    { value: 'I, V, bVII, IV' },
    { value: 'I, bVII, bVI, bVII' },
    { value: 'I, VIm, IIm, V' },
    { value: 'I, IV, IIm, V' },
    { value: 'III7, VI7, II7, V7' },
    { value: 'bVI, bVII, Im, Im' },
    { value: 'VIm, V, IV, V' },
    { value: 'VIm, IV, I, V' },
    { value: 'VIm, IIIm, V, IV' },
    { value: 'VIm, III, bII, I' },
    { value: 'VIm, IIm, V, I' },
    { value: 'Im, bVI, bIII, bVII' },
    { value: 'Im, IVm, Vm, Im' },
    { value: 'Im, bVII, bVI, bVII' },
    { value: 'Im, Vm, bVII, IVm' },
    { value: 'IIm, V, I, VIm' },
    { value: 'IIm, bIIIA, I' },
  ],

  scales: [
    { value: 'major' },
    { value: 'dorian' },
    { value: 'dorian b2' },
    { value: 'dorian #4' },
    { value: 'phrygian' },
    { value: 'phrygian dominant' },
    { value: 'lydian' },
    { value: 'lydian augmented' },
    { value: 'lydian diminished' },
    { value: 'lydian dominant' },
    { value: 'mixolydian' },
    { value: 'mixolydian b6' },
    { value: 'minor' },
    { value: 'locrian' },
    { value: 'locrian #2' },

    { value: 'augmented' },
    { value: 'bebop' },
    { value: 'chromatic' },
    { value: 'diminished' },
    { value: 'enigmatic' },
    { value: 'flamenco' },
    { value: 'half-whole diminished' },
    { value: 'pelog' },
    { value: 'persian' },
    { value: 'prometheus' },
    { value: 'whole tone' },

    { value: 'major pentatonic' },
    { value: 'major blues' },
    { value: 'major augmented' },
    { value: 'harmonic major' },
    { value: 'double harmonic major' },
    { value: 'neopolitan major' },
    { value: 'bebop major' },
    { value: 'hungarian major' },
    { value: 'locrian major' },

    { value: 'minor pentatonic' },
    { value: 'minor six pentatonic' },
    { value: 'minor blues' },
    { value: 'minor hexatonic' },
    { value: 'harmonic minor' },
    { value: 'melodic minor' },
    { value: 'hungarian minor' },
  ],
};
